language: perl
perl:
    - "blead"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1 # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead     # ignores failures for blead perl

sudo: false

notifications:
    email: false
